server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true